CREATE TABLE IF NOT EXISTS `students`
(
    `id`         INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name`       TEXT        NOT NULL,
    `usn`        VARCHAR(20) NOT NULL UNIQUE,
    `email`      VARCHAR(50) NOT NULL UNIQUE,
    `phone`      VARCHAR(12) NOT NULL UNIQUE,
    `created_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
