CREATE TABLE IF NOT EXISTS `faculties`
(
    `id`          INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name`        TEXT     NOT NULL,
    `designation` TEXT     NOT NULL,
    `created_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);